name: Build and Push

on:
  push:
    branches: [ main ]

env:
  REGISTRY: hub.siel.ninja
  REPOSITORY: sealed-secrets/sealed-secrets-controller
  TAG: 0.32.2
  GO_VERSION: "1.21"
  TARGETARCH: amd64

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build controller binary
        run: |
          mkdir -p dist/controller_linux_${{ env.TARGETARCH }}
          GOOS=linux GOARCH=${{ env.TARGETARCH }} CGO_ENABLED=0 go build -ldflags="-X main.VERSION=${{ env.TAG }}" -o dist/controller_linux_${{ env.TARGETARCH }}/controller ./cmd/controller

      - name: Build Docker image
        run: |
          docker build \
            --build-arg TARGETARCH=${{ env.TARGETARCH }} \
            -t ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.TAG }} \
            -f docker/controller.Dockerfile .

      - name: Docker login
        run: |
          echo "${{ secrets.HUB_PASSWORD }}" | docker login ${{ env.REGISTRY }} -u '${{ secrets.HUB_USERNAME }}' --password-stdin

      - name: Push Docker image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.TAG }}
