name: Publish Helm Chart to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'helm/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Package Helm chart
        run: |
          mkdir -p packaged
          helm package helm/sealed-secrets -d packaged

      - name: Publish chart to GitHub Pages
        run: |
          CHART_VERSION=$(grep '^version:' helm/sealed-secrets/Chart.yaml | awk '{print $2}')
          echo "Publishing chart version $CHART_VERSION"

          # Create a temporary workdir for gh-pages branch
          mkdir gh-pages
          cd gh-pages
          git init

          # Use GITHUB_TOKEN for authentication
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git fetch origin gh-pages || true
          git checkout gh-pages || git checkout --orphan gh-pages

          # Copy packaged chart and rebuild index.yaml
          cp ../packaged/*.tgz .
          helm repo index . --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}

          # Commit and push changes
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Publish Helm chart v${CHART_VERSION}" || echo "No changes to commit"
          git push origin gh-pages
